// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileBodys.proto

package com.fileApp.pojo;

public interface FileBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fileApp.pojo.FileBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileName = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>sint32 end = 2;</code>
   * @return The end.
   */
  int getEnd();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string verCode = 4;</code>
   * @return The verCode.
   */
  java.lang.String getVerCode();
  /**
   * <code>string verCode = 4;</code>
   * @return The bytes for verCode.
   */
  com.google.protobuf.ByteString
      getVerCodeBytes();

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>int32 status = 5;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>sint64 fileLength = 6;</code>
   * @return The fileLength.
   */
  long getFileLength();
}
