// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileBodys.proto

package com.fileApp.pojo;

public final class FileHandler {
  private FileHandler() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fileApp_pojo_FileBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fileApp_pojo_FileBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017fileBodys.proto\022\020com.fileApp.pojo\"l\n\010F" +
      "ileBody\022\020\n\010fileName\030\001 \001(\t\022\013\n\003end\030\002 \001(\021\022\014" +
      "\n\004data\030\003 \001(\014\022\017\n\007verCode\030\004 \001(\t\022\016\n\006status\030" +
      "\005 \001(\005\022\022\n\nfileLength\030\006 \001(\022B\017B\013FileHandler" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_fileApp_pojo_FileBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fileApp_pojo_FileBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fileApp_pojo_FileBody_descriptor,
        new java.lang.String[] { "FileName", "End", "Data", "VerCode", "Status", "FileLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
